### PR TITLE
Add automatic autocmd creation to config

### LINKED ISSUE #32: Create autocmd in this package
Dear @kosayoda,

Would it be an idea to let the package create the autocmd, instead of the user? This requires less configuration for the user and makes the package work more 'out the box'. By giving the autocommand a group name that matches the package name, it is also more clear where the autocmd is made and belongs to. I think it's fairly easy to implement it, just add this to the setup function:

```lua
local id = vim.api.nvim_create_augroup('nvim-lightbulb', {})
vim.api.nvim_create_autocmd({'CursorHold', 'CursorHoldI'}, {
    callback = M.update_lightbulb, -- idk if M. should be used here or something else
    group = id
})
```
The drawback is that users do not have control anymore over 1) on which events it will update, and 2) on which file patterns. If you really want users to have control over this, it can be added to the config passed to the setup function.

Let me know what you think!

### PR DESCRIPTION
**Pull request by yochem**
This PR adds the default configuration for the autocmd config, a function that creates the augroup "LightBulb" and adds an autocmd to this group. This function is called in `config.setup` if `default_config.autocmd.enabled` is set to true.

I chose to use the keyword `pattern` instead of `patterns` to make it the same as the nvim API for autocmds.

Closes #32.

### CODE REVIEW

**Comment by yochem** [comment]
I tried to keep the code style as similar as possible. LMK if you want me to do something differently!

**Comment by kosayoda** [comment]
Thanks for the PR! I'll try to take a closer look as soon as possible, as I am fairly busy recently. On first glance, do you happen to know when `vim.api.nvim_create_autocmd` and `vim.api.nvim_create_augroup` were added?

**Comment by yochem** [comment]
It was added in the latest stable release: v0.7.0. This version is released 23 days ago. I could add in a check to support older versions as well if you want. I see I also forgot to update the readme to include information about this option. Will do that too.

**Comment by yochem** [comment]
Done!

**Comment by kosayoda** [comment]
Thanks for the PR!

**Pull request merged**
