### PR TITLE
feat: add virtual_text

### PR DESCRIPTION
**Pull request by tamago324**
Thanks for the great plugin!

I wanted to show the icons in virtual text, so I implemented it.

If you like it, I'd be happy to merge it.

lightbulb_pr

### CODE REVIEW

**Comment by tamago324** [comment]
I think it would be better to clear the virtual text when CursorMoved or CursorMovedI occurs, as in `lsp_util.open_floating_preview()`.
By the way, I like that better.

Please let me know your opinion.

**Review by kosayoda — APPROVED** [review]
Thanks for the pull request, and good job!

Ideally though, I'd like for the virtual text to not update if the codeAction line did not change, so there is no flickering of the lightbulb (see the `_update_sign` function for my solution to that). The current implementation is fine though, so I might just implement that in the future.

**Comment by tamago324** [comment]
Thank you for merging!

You are free to change the code as you wish.
However, I'd be happy if you could make it disappear as soon as you move the cursor, but it's a matter of preference, so don't worry about it.

**Comment by kosayoda** [comment]
> make it disappear as soon as you move the cursor

I'm not sure I understand what you mean. The sign will always disappear if you move to a new line, what I meant was moving horizontally on the same line not updating the sign if there's still a codeAction at the cursor position.
cursorMove

**Comment by tamago324** [comment]
When I looked at my vimrc, it was set to `set updatetime=400`.
With `set updatetime=400`, when I moved the cursor to another line, `virtual text` disappeared after 400 milliseconds, so I mistakenly thought it didn't disappear right after I moved the cursor.
Now that I look at it, I think the implementation of sign is more correct. Sorry.

**Comment by kosayoda** [comment]
No need to apologize ^^, it's not terribly important. You don't have to amend it if you don't want to, the feature addition is already really nice.

**Comment by tamago324** [comment]
I want to fix it.
Can I create another PullRequest and can I ask you to code review?

**Pull request merged**
